version: '3.8'

services:
  backend:
    restart: always
    build: ./backend
    container_name: free_file_archiver_backend
    ports:
      - "8000:8000"

  frontend:
    restart: always
    build: ./frontend
    container_name: free_file_archiver_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend